### ISSUE TITLE
Not compatible with prettier 2.3.1

### ISSUE THREAD

**Issue by jhiesey** [brodybits/prettier-config-x-standard#1]
When using this config, every linted file generates a "Value ... is not a valid document" error like this:

```
[error] hooks/useBreakpointValue.js: Error: Value [[["// For convenience, support passing a bare value (not an array or object)",{"type":"concat","parts":[{"type":"line","hard":true},{"type":"break-parent"}]}]],{"type":"concat","parts":[{"type":"concat","parts":["return",{"type":"concat","parts":[" ",{"type":"concat","parts":[{"type":"concat","parts":["values","",""]}]},""]}]}]},[]] is not a valid document
[error]     at assertDoc (/Users/jhiesey/Work/Socket/wormhole/node_modules/prettierx/src/document/doc-builders.js:22:11)
[error]     at Array.forEach (<anonymous>)
[error]     at concat (/Users/jhiesey/Work/Socket/wormhole/node_modules/prettierx/src/document/doc-builders.js:34:11)
[error]     at /Users/jhiesey/Work/Socket/wormhole/node_modules/prettierx/src/language-js/printer-estree.js:4063:18
[error]     at /Users/jhiesey/Work/Socket/wormhole/node_modules/prettier/index.js:14634:23
[error]     at AstPath.each (/Users/jhiesey/Work/Socket/wormhole/node_modules/prettier/index.js:14621:7)
[error]     at AstPath.map (/Users/jhiesey/Work/Socket/wormhole/node_modules/prettier/index.js:14633:10)
[error]     at printStatementSequence (/Users/jhiesey/Work/Socket/wormhole/node_modules/prettierx/src/language-js/printer-estree.js:4008:8)
[error]     at /Users/jhiesey/Work/Socket/wormhole/node_modules/prettierx/src/language-js/printer-estree.js:1248:16
[error]     at AstPath.call (/Users/jhiesey/Work/Socket/wormhole/node_modules/prettier/index.js:14588:20)
```

**Comment by brody2consult** [comment]
Needs investigation. My apologies for the delay.
